### ISSUE TITLE
Recall和SetEssenceMsg不返回结果

### ISSUE THREAD

**Issue by foxxdeluxe** [Jaffoo/ShamrockCore.NET#2]
`MessageReceiverBase`中，方法`Recall`返回值为`Task`，其所调用的方法`Api.DeleteMsg`返回值为`Task<bool>`，导致返回结果被忽略；`SetEssenceMsg`同理。

**Comment by Jaffoo** [comment]
于版本1.2.0加上，请到nuget完成下载更新
