### ISSUE TITLE
反向ws时，无法发送消息

### ISSUE THREAD

**Issue by nitlei** [Jaffoo/ShamrockCore.NET#5]
我是手机安装的openshamrock，开反向ws，能接受到消息。现在问题是想发送消息是要用第二个http端口，我设置的http端口并不能发送，每次都是等待发送无响应。openshamrock上主动http是设置的5700。
还有个问题是：这test运行时，控制台接收到消息并不会显示输出，而是我在控制台按回车才会输出或者回复，这是哪里设置不对吗？不按回车代码不运行的。
![Screenshot_20240325_115033](https://github.com/Jaffoo/ShamrockCore.NET/assets/161731456/8d4808e0-ed98-471e-8627-e85df57d6b3b)

**Comment by Jaffoo** [comment]
第一个问题：你的ip地址是192.168.0.1，请确定这个ip是你手机 **当时** 的ip（正常情况下这个地址一般是家庭路由器或者光猫使用的ip地址，所以我推测你可能IP填错了）；一般手机都是用的**dhcp**，每次连接wifi IP地址都可能会改变，建议把改手机ip改为静态（wifi设置，ip设置改为静态，填入一个不太可能和其他设备冲突的ip地址）。
第二个问题：我也不知道，我没出现过，可能是你vs出问题了？

**Comment by nitlei** [comment]
> 第一个问题：你的ip地址是192.168.0.1，请确定这个ip是你手机 **当时** 的ip（正常情况下这个地址一般是家庭路由器或者光猫使用的ip地址，所以我推测你可能IP填错了）；一般手机都是用的**dhcp**，每次连接wifi IP地址都可能会改变，建议把改手机ip改为静态（wifi设置，ip设置改为静态，填入一个不太可能和其他设备冲突的ip地址）。 第二个问题：我也不知道，我没出现过，可能是你vs出问题了？

我用的被动ws，ip用192.168.0.1监听端口就行了，ws通信是正常的，而手机并不是公网ip会随时改变的，所以我在想为何发送消息要用http端口，ws是连接上的，能直接回复消息吗？

**Comment by Jaffoo** [comment]
> 端口就行了，ws通信是正常的，而手机并不是公网ip会随时改变的，所以我在想为何发送消息要用http端口，ws是连接上的，能直

openshamrock本身是支持使用ws发送消息，我不用的原因是ws随时在接收消息，如果我使用ws发送消息，我不好确定ws接收的到消息中哪一条是我刚刚发送消息返回来响应，当然这个可以实现但是会多出额外的判断，但是如果我用http那么请求和返回是一对一的，发送一个请求，必然对应那个请求的响应，所以我好处理返回的信息。
手机IP改变的问题，你去了解以下DHCP这个协议，并不是说是公网才用这个协议，内网也用，一般家庭路由器/支持路由的光猫默认都是这个协议，由于内网设备可能出现IP冲突的情况，普通人也不懂，所以内网设备的IP都是通过DHCP协议自动分配的，也就是说，设备IP如果不是静态的，可能会出现每次重新连接wifi，IP和上一次都不一样的情况。

**Comment by Jaffoo** [comment]
如果还有问题，建议加群，群里问或者私聊我，效率更高
